### ISSUE TITLE
[Question] Confusion about chisel-tms command

### ISSUE THREAD

**Issue by XiaoliChan** [m3rcer/Chisel-Strike#2]
Basic information
```
CobaltStrike version: 4.2
CobaltStrike Teamserver system: ubuntu 20.0.4
CobaltStrike client system: windows 10

```
Hello dude, I am now confused about this command: how did it execute the chisel in teamserver?

As you can see, the chisel is running on the CS client.

- chisel-tms
![image](https://user-images.githubusercontent.com/30458572/187477343-68030f7a-b04c-44f4-9cf3-25a216b6a7be.png)
![image](https://user-images.githubusercontent.com/30458572/187477965-23092611-d46f-4c77-a661-cd17afba0e73.png)

Any CS version limit? Hers is my CS version.
![image](https://user-images.githubusercontent.com/30458572/187478262-305277ef-2c11-4d3f-a470-7779b478eaec.png)

**Comment by XiaoliChan** [comment]
I just tested CS 4.3 version, same situation.

**Comment by m3rcer** [comment]
This should work fine on most versions. So basically there are two commands to setup the chisel pivot: 

`chisel`: Executes chisel on your beacon

`chisel-tms`: Executes chisel on your CS teamserver

1. Setup a chisel server on your CS Teamserver using a command such as `chisel-tms server -p 8081`

2. Next connect back to your chisel teamserver hosted on your CS Teamserver using: `chisel client <IP:Port> R:socks` 

This way you can setup a basic chisel pivot. You can also go ahead and do the opposite setting up a chisel server on your beacon host and make your teamserver connect back to it to perform a reverse pivot.

**Comment by XiaoliChan** [comment]
Yep, I also think `chisel-tms` should execute chisel server on my CS teamserver.

But as you can see, it executed on the CS client side, not CS teamserver.

**Comment by XiaoliChan** [comment]
You can see the first screenshot, it said "executing on windows 10 teamserver", but this environment is my CS client, my CS teamserver is actually an Ubuntu system

**Comment by m3rcer** [comment]
Ah, I see...

So it setup something similar:

```
Teamserver: Ubuntu 18.04/20.04
Client/beacon: Windows
Cobalt Strike version: 4.4
```

It seems to work fine with CS4.4+ on Ubuntu, not quite sure about CS4.2 since I don't have the version (Could be an issue since some commands used maybe introduced in later versions). You can give it a go with this [repo](https://github.com/trewisscotch/CobaltStr4.4).

![image](https://user-images.githubusercontent.com/81712403/188239269-49b70f70-575f-4fbf-bf2c-d27a753fbcf1.png)

**Comment by XiaoliChan** [comment]
> You can give it a go with this [repo](https://github.com/trewisscotch/CobaltStr4.4).

This repository has been baned.

**Comment by XiaoliChan** [comment]
I have checked your ENV, and something is wrong.

I mean CS client, not Beacon, you should try to use other machines connect to your CS teamserver, such as:
```
1, Using Kali as CS client (load chiselstrike).
2, Running teamserver on Ubuntu (like VPS).
3, Windows as victim machine (Beacon).
```
Using this setup as real cyber-attack.

In my case, execute `chisel-tms` from the CS client side (Kali machine), and you will see the chisel-server is handling on Kali, not VPS.

**Comment by m3rcer** [comment]
I now understand your issue, but by design 

> > You can give it a go with this [repo](https://github.com/trewisscotch/CobaltStr4.4).
> 
> This repository has been baned.

Seems like this repo just got taken down today, [WayBack](https://web.archive.org/web/20220000000000*/https://github.com/trewisscotch/CobaltStr4.4) is your friend.

**Comment by m3rcer** [comment]
> I have checked your ENV, and something is wrong.
> 
> I mean CS client, not Beacon, you should try to use other machines connect to your CS teamserver, such as:
> 
> ```
> 1, Using Kali as CS client (load chiselstrike).
> 2, Running teamserver on Ubuntu (like VPS).
> 3, Windows as victim machine (Beacon).
> ```
> 
> Using this setup as real cyber-attack.
> 
> In my case, execute `chisel-tms` from the CS client side (Kali machine), and you will see the chisel-server is handling on Kali, not VPS.

I now understand your issue,  by design I've programmed the `chisel-tms`  & `chisel-tms-kill` command to execute chisel on the Cobalt Strike Client not the teamserver , so in your case execution on the Kali CS Client is intended. Thanks for reporting this, I'll have the description updated for now and probably work on a separate branch to get `chisel-tms` & `chisel-tms-kill` to execute chisel on the teamserver rather the CS client.

**Comment by XiaoliChan** [comment]
The way of solution is deploy chisel server and http server(for remote loading) manually.

**Comment by m3rcer** [comment]
> The way of solution is deploy chisel server and http server(for remote loading) manually.

A suitable means would be setting up a redirector on the teamsever vps to redirect chisel traffic onto the CS Client vm where the chisel server is listening. This would be a suitable solution while using a 3 tier C2 setup as mentioned.
